### ISSUE TITLE
Collection page (ON DESKTOP)

### ISSUE THREAD

**Issue by omelki** [FadiZahhar/oldsinks#2]
On COLLECTIONS page  ((ON DESKTOP)):

1) button kitchen sinks doesn’t go to kitchen section
2) button BBQ sinks doesn’t go to BBQ section
3) When populating, images are not square anymore
4) Show only one row for instagram images
5) Footer not entered (occupies more space on the right than on the left)
6) Instagram Widget not centered
7) Make sales@ancientsfs.com clickable in Widget

8) The picture in black basalt sinks' page looks perfectly squared, make sure you apply the square property in all pages - Check both screenshots below to compare in their inspect element.

![1](https://cloud.githubusercontent.com/assets/7605683/11907650/59635406-a5de-11e5-9591-10830a93daf0.png)

![2](https://cloud.githubusercontent.com/assets/7605683/11907649/58f04d44-a5de-11e5-88e0-353c1e3328ed.png)

**Comment by FadiZahhar** [comment]
7) Make sales@ancientsfs.com clickable in Widget (done).

**Comment by FadiZahhar** [comment]
3) When populating, images are not square anymore

fixed by adding thumb image instead of medium image on page.php Ajax calls.

**Comment by FadiZahhar** [comment]
3) When populating, images are not square anymore
4) Show only one row for instagram images
5) Footer not entered (occupies more space on the right than on the left)
6) Instagram Widget not centered

fixed.

**Comment by FadiZahhar** [comment]
The jquery is not working online, need to put it somewhere else to fire... will figure it out tomorrow and close this issue related to the navigation.

**Comment by scarletmounzer** [comment]
Fadi this is one of the main issues why I can't go to the client yet and
get paid because it's a too obvious mistake.
Please can we figure it out today so that I can go to the client tomorrow
and collect the payment?

**Comment by FadiZahhar** [comment]
Issue fixed by replacing the JavaScript from front-page to footer, also adding the switch statement in the hash-change method instead of outside the scope of the function.
