### ISSUE TITLE
Collection page (ON SMALLER SCREENS)

### ISSUE THREAD

**Issue by omelki** [FadiZahhar/oldsinks#3]
On Collection page (ON SMALLER SCREENS):

1) Remove sub menu for BBQ Sinks.

2) from 992 to 1000px: subcategories show on the left AND under the title (please make it this way for all bigger sizes but remove the plus button).

3)As of 769px: remove letter spacing from sub menu (the word under the big title and the ones in the (+) menu).

4) As of 610px: Let Testimonial be with no margin (starts more on the left and finishes more on the right) (Use same as Blog page).

5) From 401px to 436px: Images in Kitchen Sinks and BBQ Sinks are not equally spaced from the middle (the white space in the middle disappears).

6) At 400px: White space in the middle of images for Kitchen Sinks and BBQ Sinks is too big.

7) At 400px: Logo in the top bar sticks to email

8) Footer not centered

**Comment by FadiZahhar** [comment]
fixed
