### ISSUE TITLE
ON Collection page 

### ISSUE THREAD

**Issue by omelki** [FadiZahhar/oldsinks#9]
Go to COLLECTIONS –> BATHROOM SINKS –> SHELL STONE SINKS

Check the screenshot there is a bug - the menu for kitchen sinks is not in its place. Pls advise!

![screen-shot-2015-12-21-at-4 51 02-pm](https://cloud.githubusercontent.com/assets/7605683/11933239/59396b9c-a803-11e5-9df3-2ecc429dddc9.jpg)

**Comment by FadiZahhar** [comment]
fixed.
